#!/usr/bin/env python3
"""news-articles -- generated newspaper articles for the daily digest.

Operator directive 2026-09-12 ("still not quite anything like a
newspaper"): the day's TOP ranked Deck-A items gain procedurally
constructed short articles (120-200 words) generated by the model chain
and committed under docs/articles/<date>/<slug>.md. Built FROM the item
data (headline, severity tag, source URL) plus the linked source page
when fetchable (ONE bounded GET, 10s timeout, meta description / first
paragraph only; failure -> article from wire data alone). Fabrication is
forbidden: nothing beyond the cited headline/source data; gaps read
"unverified per source" (docs/records gag-manga attribution discipline).
Voice: docs/design/writing-register.md law + the house deadpan closer
(the mundane played absolutely straight, operator steer 2026-09-12).

Budget: cap 6 articles/UTC day (cadence-params row
newspaper-articles-cap); local model leg preferred, quota legs rotate per
the existing share rows (kimi/ocgo research-share + run counter). Top 3
articles per edition get ONE image each via jobs/imagegen-submit.sh
(style row news-illustration, 768x512) into docs/media/news/ --
fail-closed: no image when the leg is down. Seams (tests, hermetic):
HNGH_AUTOMATION_ROOT, NEWS_ARTICLES_CAP, NEWS_ARTICLES_MODEL_CMD,
NEWS_ARTICLES_IMAGEGEN_CMD, NEWS_ARTICLES_FETCH=0.

usage: jobs/news-articles.py <YYYY-MM-DD> [--digest PATH]
"""
import json
import os
import re
import subprocess
import sys
import urllib.request

ROOT = os.environ.get("HNGH_AUTOMATION_ROOT") or os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))
REPO = os.environ.get("HNGH_REPO_ROOT") or os.path.dirname(ROOT)
DIGESTS = os.path.join(ROOT, "digest")
ARTICLES = os.path.join(REPO, "docs", "articles")
IMAGES = os.path.join(REPO, "docs", "media", "news")
IMAGEGEN = os.path.join(ROOT, "jobs", "imagegen-submit.sh")
MODEL_BUDGET = "1024"
IMAGE_BUDGET = 3
FETCH_TIMEOUT = 10


def _ascii(text):
    return str(text).encode("ascii", "replace").decode("ascii")


def get_param(key, default):
    """cadence-params.tsv row -> value; fail-open to default."""
    try:
        with open(os.path.join(ROOT, "cadence-params.tsv"),
                  encoding="utf-8") as f:
            for line in f:
                p = line.rstrip("\n").split("\t")
                if p and p[0] == key and len(p) > 1 and p[1]:
                    return p[1]
    except OSError:
        pass
    return default


_DH = None


def digest_html():
    """Load jobs/digest-html.py for its shared section parser and
    deterministic headline split (the same data law as the editions)."""
    global _DH
    if _DH is None:
        import importlib.machinery
        import importlib.util
        loader = importlib.machinery.SourceFileLoader(
            "hngh_digest_html", os.path.join(ROOT, "jobs", "digest-html.py"))
        spec = importlib.util.spec_from_loader("hngh_digest_html", loader)
        _dh = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(_dh)
    return _dh


TAG_RANK = {"CRITICAL": 0, "NOTABLE": 1, "CONTEXT": 2}
URL_RE = re.compile(r"\((https?://[^)]+)\)\s*$")
PLACE_RE = re.compile(r"^[A-Z][A-Z-]+ ([A-Z][A-Z0-9 /&'.-]+):\s")


def collect_items(digest_path):
    """Digest text -> ranked story items: [{tag, head, rest, url, time,
    sources, place}]. CRITICAL first, then NOTABLE, CONTEXT; stable
    within a band, headline-deduped. Quiet windows skipped."""
    dh = digest_html()
    with open(digest_path, encoding="utf-8") as f:
        sections = dh.parse_sections(f.read())
    seen, items = set(), []
    for s in sections:
        if s["mega"] or not s["items"]:
            continue
        for line in s["items"]:
            if "quiet window" in line:
                continue
            tag = ""
            for t in ("CRITICAL", "NOTABLE", "CONTEXT"):
                if line.startswith(t + ": "):
                    tag, body = t, line[len(t) + 2:]
                    break
            else:
                continue
            m = URL_RE.search(body)
            url = m.group(1) if m else ""
            head, rest = dh.split_headline(body)
            # the display title strips a trailing source URL; the
            # digest_headline join key keeps the exact split-headline text
            title = URL_RE.sub("", head).strip() if m else head
            if not head or head.lower() in seen:
                continue
            seen.add(head.lower())
            p = PLACE_RE.match(head)
            items.append({"tag": tag, "head": head, "title": title,
                          "rest": rest, "url": url, "time": s["time"],
                          "sources": s["sources"],
                          "place": p.group(1).title() if p else ""})
    items.sort(key=lambda i: TAG_RANK[i["tag"]])
    return items


def fetch_source(url):
    """ONE bounded GET of the item's source page -> text extract (meta
    description / og:description, else the first <p>), or None. Bounded:
    http(s) only, standard ports only (never localhost/private), 10s
    timeout, 256KB read cap. Fail-closed: any problem -> None."""
    m = re.match(r"^https?://[^/]+(:\d+)?/", url or "")
    if not m:
        return None
    if m.group(1) and m.group(1) not in (":80", ":443"):
        return None
    try:
        req = urllib.request.Request(url, headers={
            "User-Agent": "hngh-wire-desk/1.0 (newspaper)"})
        with urllib.request.urlopen(req, timeout=FETCH_TIMEOUT) as r:
            raw = r.read(262144)
    except Exception:
        return None
    text = raw.decode("utf-8", "replace")
    for pat in (r'<meta[^>]+name="description"[^>]+content="([^"]*)"',
                r'<meta[^>]+property="og:description"[^>]+content="([^"]*)"',
                r"<p>[^<]{80,}</p>"):
        m = re.search(pat, text, re.I | re.S)
        if not m:
            continue
        out = re.sub(r"<[^>]+>", " ", m.group(0))
        out = re.sub(r"\s+", " ", out).strip()
        if len(out) > 60:
            return _ascii(out)[:1200]
    return None


def build_prompt(item, source_text, ledger_line):
    """The article prompt: story data + register law + deadpan-closer
    guidance. The data block is the ONLY permitted fact source."""
    src = ("SOURCE PAGE TEXT (verbatim extract, may be truncated):\n%s"
           % source_text) if source_text else \
        "SOURCE PAGE: unreachable; article comes from the wire data alone."
    return """You are the wire desk of The Machine Hall Daily Dispatch,
filing one short front-page article.

STORY DATA (the only facts you may use):
headline: %s
severity screen: %s
place: %s
source article: %s
newsroom ledger (hngh's own machine, use ONLY if genuinely relevant): %s
%s

House law (writing register, LAW):
- Concrete nouns, active verbs; the technical word over the abstraction.
- No significance adjectives (nothing is historic/major/crucial); no
  weather opening; adverbs rare; no adjective without evidence above.
- Prefer the smaller true statement to the larger vague one.
- Inverted pyramid: what happened -> key details -> context.
- One closing/context line MAY carry the paper's deadpan craft register
  (the mundane played absolutely straight, wit from restraint) as a
  quiet factual observation grounded in the data. Never a joke, never
  mockery of any subject, never at a person's expense.
- 120-200 words, plain prose paragraphs, ASCII only. No title, no
  dateline: body text only.
- At most ONE quote, only if present verbatim in the source page text.
- Never invent names, numbers, quotes, or events beyond the data above;
  unverifiable gaps read "unverified per source".

File the article now.""" % (item["title"], item["tag"],
                            item["place"] or "unlisted",
                            item["url"] or "none",
                            ledger_line or "none on record", src)


def pick_pin():
    """MODEL_PIN: env override wins; else the existing share rotations
    (kimi, then ocgo, on the shared run counter); else local preferred."""
    env = os.environ.get("MODEL_PIN")
    if env:
        return env
    try:
        n = int(open(os.path.join(ROOT, "state",
                                  "news-articles-count")).read().strip())
    except (OSError, ValueError):
        n = 0
    for key in ("kimi-research-share", "opencode-research-share"):
        share = get_param(key, "0")
        if share.isdigit() and int(share) > 0 and (n + 1) % int(share) == 0:
            return key.split("-")[0]
    return "local"


def model_reply(prompt, pin):
    """One chain call through lib/model.sh model_call (the research-beat
    seam). Returns the text or '' (archive-only = no article; the job
    never fabricates a fallback)."""
    cmd = os.environ.get("NEWS_ARTICLES_MODEL_CMD") or \
        '. "%s/lib/model.sh"; model_call %s' % (ROOT, MODEL_BUDGET)
    env = dict(os.environ)
    env.update({"AUTOMATION_ROOT": ROOT, "MODEL_PIN": pin,
                "STATE_FILE": os.path.join(ROOT, "STATE.md")})
    env.pop("MODEL_USED", None)
    try:
        r = subprocess.run(["bash", "-c", cmd], input=prompt,
                           capture_output=True, text=True, timeout=330,
                           env=env)
    except (OSError, subprocess.TimeoutExpired):
        return ""
    used = ""
    try:
        with open(os.path.join(ROOT, "tmp-modelused.txt")) as f:
            used = f.read().strip()
    except OSError:
        pass
    if not r.stdout.strip() or used.endswith("archive-only"):
        return ""
    text = re.sub(r"^```[a-z]*\n|\n```$", "", r.stdout.strip())
    text = _ascii(text).strip()
    if text[-1] not in ".!?\"'":
        # a mid-sentence model stop never publishes: cut to the last
        # complete sentence (attribution footer still marks the gaps)
        cut = text.rfind(". ")
        if cut > 80:
            text = text[:cut + 1].strip()
    return text


def make_image(subject):
    """ONE scene illustration via jobs/imagegen-submit.sh (style
    news-illustration, 768x512) into docs/media/news/. Returns the
    repo-relative path or None (fail-closed: leg down = headline-only)."""
    cmd = os.environ.get("NEWS_ARTICLES_IMAGEGEN_CMD") or IMAGEGEN
    os.makedirs(IMAGES, exist_ok=True)
    try:
        r = subprocess.run(
            [cmd, "--style", "news-illustration", "--subject", subject,
             "--out-dir", IMAGES], capture_output=True, text=True,
            timeout=180)
    except (OSError, subprocess.TimeoutExpired):
        return None
    m = re.search(r"wrote (\S+\.png)", r.stdout + r.stderr)
    rel = os.path.relpath(m.group(1), REPO) if m else ""
    return rel.replace(os.sep, "/") if rel.startswith("docs/") else None


def slugify(head):
    words = re.findall(r"[A-Za-z0-9]+", head.lower())[:5]
    return "-".join(words) or "wire-item"


def ledger_line(dh_sections):
    """The day's metered-spend line (Deck B telemetry), for the optional
    hngh-ledger context in the prompt; None when absent."""
    for s in dh_sections:
        if s["mega"]:
            for it in s["items"]:
                if it.startswith("- spend:"):
                    return it[2:].strip()
    return ""


def write_article(date, item, body, image, used):
    """Commit one article under docs/articles/<date>/<slug>.md.
    Returns the file path. The first comment carries the metadata the
    editions read back (digest-headline joins the Deck-A item)."""
    slug = slugify(item["title"])
    meta = {"date": date, "slug": slug,
            "digest_headline": item["head"], "url": item["url"],
            "place": item["place"], "provenance": item["provenance"],
            "model": used, "image": image}
    src_note = ("the cited source page" if item["provenance"] == "source"
                else "wire data alone (source page unreachable)")
    lines = ["<!-- article: %s -->" % json.dumps(meta, sort_keys=True),
             "", "# %s" % item["title"], ""]
    if item["place"]:
        lines += ["%s -- %s --" % (item["place"], date), ""]
    lines += [body, "", "--", "", "Filed by the hngh wire desk from GDELT "
              "2.0 event data and %s. Nothing beyond the cited data is "
              "asserted; gaps read \"unverified per source\". Model draft: "
              "%s." % (src_note, used or "unattributed"), ""]
    d = os.path.join(ARTICLES, date)
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, slug + ".md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def generate(date, digest_path=None):
    """The edition run: rank the digest, cap against the day's committed
    articles, generate + commit each, image the top 3. Returns the new
    article paths."""
    digest_path = digest_path or os.path.join(DIGESTS, date + ".md")
    cap = os.environ.get("NEWS_ARTICLES_CAP") or \
        get_param("newspaper-articles-cap", "6")
    cap = int(cap) if cap.isdigit() else 6
    dh = digest_html()
    with open(digest_path, encoding="utf-8") as f:
        ledger = ledger_line(dh.parse_sections(f.read()))
    d = os.path.join(ARTICLES, date)
    existing = sorted(os.listdir(d)) if os.path.isdir(d) else []
    room = max(0, cap - len(existing))
    made, images = [], 0
    for item in collect_items(digest_path):
        if len(made) >= room:
            break
        source_text = None
        if os.environ.get("NEWS_ARTICLES_FETCH") != "0":
            source_text = fetch_source(item["url"])
        item["provenance"] = "source" if source_text else "wire"
        body = model_reply(build_prompt(item, source_text, ledger),
                           pick_pin())
        if not body:
            continue  # chain down: fail-closed, never fabricate
        image = None
        if images < IMAGE_BUDGET:
            image = make_image(item["title"][:120])
            if image:
                images += 1
        made.append(write_article(date, item, body, image,
                                  _last_used()))
    try:
        n = int(open(os.path.join(ROOT, "state",
                                  "news-articles-count")).read().strip())
    except (OSError, ValueError):
        n = 0
    os.makedirs(os.path.join(ROOT, "state"), exist_ok=True)
    with open(os.path.join(ROOT, "state", "news-articles-count"),
              "w") as f:
        f.write(str(n + 1))
    return made


def _last_used():
    try:
        with open(os.path.join(ROOT, "tmp-modelused.txt")) as f:
            return f.read().strip()
    except OSError:
        return ""


if __name__ == "__main__":
    if len(sys.argv) < 2 or not re.match(r"^\d{4}-\d{2}-\d{2}$", sys.argv[1]):
        print(__doc__.strip(), file=sys.stderr)
        sys.exit(2)
    dp = sys.argv[3] if len(sys.argv) > 3 and sys.argv[2] == "--digest" \
        else None
    for p in generate(sys.argv[1], dp):
        print(p)
