(in-package :hngh.tests)

;;;; admit-transport: Layer-2 application tests.
;;;; Style mirrors tests/application/test-arm-run.lisp: wrapper
;;;; accessors via application-call, fake ports built with
;;;; MAKE-RUN-ADMISSION-PORTS, assertions via check.

(defun admit-result-status (result)
  (application-call "APPLICATION-RESULT-STATUS" result))

(defun admit-result-run (result)
  (application-call "APPLICATION-RESULT-RUN" result))

(defun admit-result-receipt (result)
  (application-call "APPLICATION-RESULT-RECEIPT" result))

(defun admit-result-labels (result)
  (application-call "APPLICATION-RESULT-LABELS" result))

(defun admit-with (ports run transport &optional scope)
  (application-call "ADMIT-TRANSPORT" ports run transport scope))

(defun make-admit-fake (&key (timestamp "2026-08-23T00:00:00Z")
                          (record-results '(:recorded)))
  (let ((clock-calls 0)
        (record-calls 0)
        (runs '())
        (receipts '())
        (remaining (copy-list record-results)))
    (values
     (application-call
      "MAKE-RUN-ADMISSION-PORTS"
      :admission-facts (lambda (run) (declare (ignore run)) nil)
      :clock-now (lambda () (incf clock-calls) timestamp)
      :record-run (lambda (run receipt)
                    (incf record-calls)
                    (let ((result (pop remaining)))
                      (when (eql result :recorded)
                        (setf runs (append runs (list run))
                              receipts (append receipts (list receipt))))
                      result)))
     (lambda ()
       (list :clock-calls clock-calls
             :record-calls record-calls
             :runs (copy-list runs)
             :receipts (copy-list receipts))))))

(defun admit-port-ports (&key timestamp record-run clock-now)
  (application-call
   "MAKE-RUN-ADMISSION-PORTS"
   :admission-facts (lambda (run) (declare (ignore run)) nil)
   :clock-now (or clock-now (lambda () (or timestamp "2026-08-23T00:00:00Z")))
   :record-run (or record-run
                   (lambda (run receipt)
                     (declare (ignore run receipt))
                     :recorded))))

(defun admission-receipt-facts (result)
  (hngh.domain:receipt-facts (admit-result-receipt result)))

(check (not (null (find-symbol "ADMIT-TRANSPORT" "HNGH.APPLICATION")))
       "admit-transport resolves in the application package")

(let* ((run (created-application-run)))
  (multiple-value-bind (ports reporter) (make-admit-fake)
    (let ((result (admit-with ports run :filesystem "repository")))
      (check (eq :accepted (admit-result-status result))
             "filesystem transport is admitted")
      (check (null (admit-result-labels result))
             "accepted admission carries no labels")
      (check (eq run (admit-result-run result))
             "accepted admission returns the same run")
      (check (eq :created (hngh.domain:run-state run))
             "admission leaves the run :created")
      (check (not (null (admit-result-receipt result)))
             "accepted admission carries a receipt")
      (check (eq :admission (hngh.domain:receipt-kind (admit-result-receipt result)))
             "receipt kind is :admission")
      (check (equal '("transport: filesystem"
                      "scope: repository"
                      "route: local"
                      "run: run-application-1"
                      "timestamp: 2026-08-23T00:00:00Z")
                    (admission-receipt-facts result))
             "admission receipt records transport, scope, route, run, timestamp")
      (check (equal '("admitted") (application-call "APPLICATION-RESULT-FACTS" result))
             "accepted admission result facts name the admission")
      (let ((state (funcall reporter)))
        (check (= 1 (getf state :clock-calls))
               "admission consults the clock exactly once")
        (check (= 1 (getf state :record-calls))
               "admission records exactly one pair")
        (check (and (= 1 (length (getf state :runs)))
                    (eq run (first (getf state :runs))))
               "recorded run is the admitted run")
        (check (and (= 1 (length (getf state :receipts)))
                    (eq (admit-result-receipt result)
                        (first (getf state :receipts))))
               "recorded receipt is the returned receipt")))))

(let* ((run (hngh.domain:advance-run (created-application-run) :armed)))
  (multiple-value-bind (ports reporter) (make-admit-fake)
    (let ((result (admit-with ports run :filesystem "repository")))
      (check (eq :accepted (admit-result-status result))
             "an armed run is admitted")
      (check (eq :armed (hngh.domain:run-state run))
             "admission leaves an armed run armed")
      (check (equal '("timestamp: 2026-08-23T00:00:00Z")
                    (last (admission-receipt-facts result) 1))
             "armed admission receipt still carries the clock timestamp"))))

(multiple-value-bind (ports reporter) (make-admit-fake)
  (let ((result (admit-with ports (created-application-run) :filesystem)))
    (check (eq :accepted (admit-result-status result))
           "omitted scope defaults to the first writable scope")
    (check (equal '("transport: filesystem"
                    "scope: repository"
                    "route: local"
                    "run: run-application-1"
                    "timestamp: 2026-08-23T00:00:00Z")
                  (admission-receipt-facts result))
           "defaulted scope receipt records the loadout's first writable scope")))

(multiple-value-bind (ports reporter) (make-admit-fake)
  (let ((result (admit-with ports (created-application-run) :mutation "repository")))
    (check (eq :refused (admit-result-status result))
           "unknown transport is refused")
    (check (member "unknown-transport" (admit-result-labels result) :test #'string=)
           "unknown transport refusal carries its label")
    (check (null (admit-result-run result))
           "unknown transport refusal carries no run")
    (check (null (admit-result-receipt result))
           "unknown transport refusal carries no receipt")
    (let ((state (funcall reporter)))
      (check (zerop (getf state :clock-calls))
             "unknown transport refusal does not consult the clock")
      (check (zerop (getf state :record-calls))
             "unknown transport refusal records nothing"))))

(multiple-value-bind (ports reporter) (make-admit-fake)
  (let ((result (admit-with ports (created-application-run) :not-a-transport nil)))
    (check (eq :refused (admit-result-status result))
           "malformed transport keyword is refused")
    (check (member "unknown-transport" (admit-result-labels result) :test #'string=)
           "malformed transport carries the unknown-transport label")
    (check (null (admit-result-receipt result))
           "malformed transport refusal carries no receipt")))

(let* ((run (hngh.domain:advance-run
             (hngh.domain:advance-run (created-application-run) :armed)
             :running)))
  (multiple-value-bind (ports reporter) (make-admit-fake)
    (let ((result (admit-with ports run :filesystem "repository")))
      (check (eq :refused (admit-result-status result))
             "a run that is not :created or :armed is refused")
      (check (member "invalid-transition" (admit-result-labels result) :test #'string=)
             "invalid state refusal carries its label")
      (check (null (admit-result-run result))
             "invalid state refusal carries no run")
      (check (null (admit-result-receipt result))
             "invalid state refusal carries no receipt")
      (let ((state (funcall reporter)))
        (check (zerop (getf state :clock-calls))
               "invalid state refusal does not consult the clock")
        (check (zerop (getf state :record-calls))
               "invalid state refusal records nothing")))))

(multiple-value-bind (ports reporter) (make-admit-fake)
  (let ((result (admit-with ports (created-application-run) :filesystem "staging")))
    (check (eq :refused (admit-result-status result))
           "a scope outside the loadout's writable-scopes is refused")
    (check (member "unauthorized-scope" (admit-result-labels result) :test #'string=)
           "unauthorized scope refusal carries its label")
    (check (null (admit-result-run result))
           "unauthorized scope refusal carries no run")
    (check (null (admit-result-receipt result))
           "unauthorized scope refusal carries no receipt")
    (let ((state (funcall reporter)))
      (check (zerop (getf state :clock-calls))
             "unauthorized scope refusal does not consult the clock")
      (check (zerop (getf state :record-calls))
             "unauthorized scope refusal records nothing"))))

(multiple-value-bind (ports reporter)
    (make-admit-fake :record-results '(:recorded :conflict))
  (let* ((run (created-application-run))
         (first-result (admit-with ports run :filesystem "repository")))
    (check (eq :accepted (admit-result-status first-result))
           "first admission of a (run, transport) pair is accepted")
    (let ((second-result (admit-with ports run :filesystem "repository")))
      (check (eq :conflict (admit-result-status second-result))
             "duplicate (run, transport) admission is a conflict")
      (check (member "duplicate-admission" (admit-result-labels second-result)
                     :test #'string=)
             "duplicate admission carries its label")
      (check (null (admit-result-run second-result))
             "conflicted admission carries no run")
      (check (null (admit-result-receipt second-result))
             "conflicted admission carries no receipt")
      (check (equal '("admitted") (application-call "APPLICATION-RESULT-FACTS" first-result))
             "accepted admission still carries result facts")
      (let ((state (funcall reporter)))
        (check (= 2 (getf state :record-calls))
               "duplicate admission calls record twice")
        (check (and (= 1 (length (getf state :runs)))
                    (= 1 (length (getf state :receipts))))
               "conflict records no extra pair")))))

(multiple-value-bind (ports reporter) (make-admit-fake :record-results '(:weird))
  (let ((result (admit-with ports (created-application-run) :filesystem "repository")))
    (check (eq :refused (admit-result-status result))
           "an unknown record answer refuses admission")
    (check (member "callback-contract" (admit-result-labels result) :test #'string=)
           "unknown record answer carries the callback label")
    (check (null (admit-result-run result))
           "unknown record answer carries no run")
    (check (null (admit-result-receipt result))
           "unknown record answer carries no receipt")))

(let ((ports (admit-port-ports
              :clock-now (lambda () (error "clock failure")))))
  (let ((result (admit-with ports (created-application-run) :filesystem "repository")))
    (check (eq :refused (admit-result-status result))
           "clock callback errors refuse admission")
    (check (member "callback-contract" (admit-result-labels result) :test #'string=)
           "clock error refusal carries the callback label")
    (check (null (admit-result-run result))
           "clock error refusal carries no run")
    (check (null (admit-result-receipt result))
           "clock error refusal carries no receipt")))

(let ((ports (admit-port-ports
              :record-run (lambda (run receipt)
                            (declare (ignore run receipt))
                            (error "record failure")))))
  (let ((result (admit-with ports (created-application-run) :filesystem "repository")))
    (check (eq :refused (admit-result-status result))
           "record callback errors refuse admission")
    (check (member "callback-contract" (admit-result-labels result) :test #'string=)
           "record error refusal carries the callback label")
    (check (null (admit-result-run result))
           "record error refusal carries no run")
    (check (null (admit-result-receipt result))
           "record error refusal carries no receipt")))

(let ((ports (application-call
              "MAKE-RUN-ADMISSION-PORTS"
              :admission-facts (lambda (run) (declare (ignore run)) nil)
              :record-run (lambda (run receipt)
                            (declare (ignore run receipt))
                            :recorded))))
  (let ((result (admit-with ports (created-application-run) :filesystem "repository")))
    (check (eq :refused (admit-result-status result))
           "admission without a clock is refused")
    (check (member "callback-contract" (admit-result-labels result) :test #'string=)
           "clockless admission carries the callback label")
    (check (null (admit-result-run result))
           "clockless admission carries no run")
    (check (null (admit-result-receipt result))
           "clockless admission carries no receipt")))

(check (signals-error-p
        (lambda () (admit-with :not-ports (created-application-run)
                               :filesystem "repository")))
       "admit-transport rejects missing ports")