(in-package :hngh.tests)

(defun checkpoint-run-with (ports run)
  (application-call "CHECKPOINT" ports run))

(defun running-application-run ()
  (hngh.domain:advance-run (armed-application-run) :running))

(defun checkpoint-result-status (result)
  (application-result-value "APPLICATION-RESULT-STATUS" result))

(defun checkpoint-result-run (result)
  (application-result-value "APPLICATION-RESULT-RUN" result))

(defun checkpoint-result-receipt (result)
  (application-result-value "APPLICATION-RESULT-RECEIPT" result))

(defun verification-result-with (&key (status :passed) (labels '("tests-pass")))
  (application-call "MAKE-VERIFICATION-RESULT" :status status :labels labels))

(defun manifest-result-with (&key (status :complete) (labels '("manifest-complete")))
  (application-call "MAKE-MANIFEST-RESULT" :status status :labels labels))

(dolist (status '(:passed :failed :unknown))
  (let ((result (verification-result-with :status status)))
    (check (eql status
                (application-call "VERIFICATION-RESULT-STATUS" result))
           "verification result preserves its closed status")))

(dolist (status '(:complete :incomplete :unknown))
  (let ((result (manifest-result-with :status status)))
    (check (eql status (application-call "MANIFEST-RESULT-STATUS" result))
           "manifest result preserves its closed status")))

(dolist (arguments
         (list '()
               (list :status :invalid :labels '("label"))
               (list :status :passed :labels nil)
               (list :status :passed :labels '())
               (list :status :passed :labels '(""))
               (list :status :passed :labels "label")))
  (check (signals-error-p
          (lambda ()
            (apply (application-function "MAKE-VERIFICATION-RESULT") arguments)))
         "verification results reject malformed status and labels"))

(dolist (arguments
         (list '()
               (list :status :invalid :labels '("label"))
               (list :status :complete :labels nil)
               (list :status :complete :labels '())
               (list :status :complete :labels '(""))
               (list :status :complete :labels "label")))
  (check (signals-error-p
          (lambda ()
            (apply (application-function "MAKE-MANIFEST-RESULT") arguments)))
         "manifest results reject malformed status and labels"))

(let ((result (verification-result-with :labels '("immutable"))))
  (let ((labels (application-call "VERIFICATION-RESULT-LABELS" result)))
    (setf (first labels) "changed")
    (check (equal '("immutable")
                  (application-call "VERIFICATION-RESULT-LABELS" result))
           "verification result labels are defensive copies")))

(let ((result (manifest-result-with :labels '("immutable"))))
  (let ((labels (application-call "MANIFEST-RESULT-LABELS" result)))
    (setf (first labels) "changed")
    (check (equal '("immutable")
                  (application-call "MANIFEST-RESULT-LABELS" result))
           "manifest result labels are defensive copies")))

(dolist (arguments
         (list '()
               (list :run :invalid)))
  (check (signals-error-p
          (lambda ()
            (apply (application-function "MAKE-CHECKPOINT-REQUEST") arguments)))
         "checkpoint requests reject missing or non-run inputs"))

(let* ((run (running-application-run))
       (request (application-call "MAKE-CHECKPOINT-REQUEST" :run run)))
  (check (eq run (application-call "CHECKPOINT-REQUEST-RUN" request))
         "checkpoint request contains its domain run"))

(dolist (arguments
         (list '()
               (list :repository-inspector (lambda (request)
                                             (declare (ignore request))
                                             (manifest-result-with))
                     :record-run (lambda (run receipt)
                                   (declare (ignore run receipt))
                                   :recorded))
               (list :tool-executor (lambda (request)
                                      (declare (ignore request))
                                      (verification-result-with))
                     :record-run (lambda (run receipt)
                                   (declare (ignore run receipt))
                                   :recorded))
               (list :tool-executor (lambda (request)
                                      (declare (ignore request))
                                      (verification-result-with))
                     :repository-inspector (lambda (request)
                                             (declare (ignore request))
                                             (manifest-result-with))
                     :record-run :invalid)
               (list :tool-executor :invalid
                     :repository-inspector (lambda (request)
                                             (declare (ignore request))
                                             (manifest-result-with))
                     :record-run (lambda (run receipt)
                                   (declare (ignore run receipt))
                                   :recorded))))
  (check (signals-error-p
          (lambda ()
            (apply (application-function "MAKE-RUN-CHECKPOINT-PORTS") arguments)))
         "checkpoint ports reject missing or non-function callbacks"))

(dolist (extra-keyword '(:model-completion :renderer))
  (check (signals-error-p
          (lambda ()
            (apply (application-function "MAKE-RUN-CHECKPOINT-PORTS")
                   (list
                    :tool-executor (lambda (request)
                                     (declare (ignore request))
                                     (verification-result-with))
                    :repository-inspector (lambda (request)
                                            (declare (ignore request))
                                            (manifest-result-with))
                    :record-run (lambda (run receipt)
                                  (declare (ignore run receipt))
                                  :recorded)
                    extra-keyword (lambda () :forbidden)))))
         "checkpoint ports admit no model or renderer callback"))

(multiple-value-bind (ports snapshot)
    (make-checkpoint-fake)
  (let ((result (checkpoint-run-with ports (running-application-run)))
        (state (funcall snapshot)))
    (check (eql :accepted (checkpoint-result-status result))
           "complete checkpoint evidence is accepted")
    (check (eql :checkpointed
                (hngh.domain:run-state (checkpoint-result-run result)))
           "complete checkpoint evidence returns a checkpointed run")
    (check (not (null (checkpoint-result-receipt result)))
           "complete checkpoint evidence returns a receipt")
    (check (= 1 (getf state :tool-calls))
           "checkpoint invokes tool evidence once")
    (check (= 1 (getf state :repository-calls))
           "checkpoint invokes repository evidence once")
    (check (= 1 (getf state :record-calls))
           "checkpoint records once")
    (check (eq (first (getf state :runs)) (checkpoint-result-run result))
           "checkpoint records its returned run")
    (check (eq (first (getf state :receipts)) (checkpoint-result-receipt result))
           "checkpoint records its returned receipt")))

(dolist (verification-status '(:failed :unknown))
  (multiple-value-bind (ports snapshot)
      (make-checkpoint-fake
       :verification (verification-result-with :status verification-status))
    (let* ((run (running-application-run))
           (result (checkpoint-run-with ports run))
           (state (funcall snapshot)))
      (check (eql :refused (checkpoint-result-status result))
             "failed or unknown verification is refused")
      (check (eql :running (hngh.domain:run-state run))
             "failed or unknown verification preserves the source run")
      (check (= 1 (getf state :tool-calls))
             "failed or unknown verification invokes tool evidence once")
      (check (= 1 (getf state :repository-calls))
             "failed or unknown verification invokes repository evidence once")
      (check (zerop (getf state :record-calls))
             "failed or unknown verification does not record"))))

(dolist (manifest-status '(:incomplete :unknown))
  (multiple-value-bind (ports snapshot)
      (make-checkpoint-fake
       :manifest (manifest-result-with :status manifest-status))
    (let* ((run (running-application-run))
           (result (checkpoint-run-with ports run))
           (state (funcall snapshot)))
      (check (eql :refused (checkpoint-result-status result))
             "incomplete or unknown manifest is refused")
      (check (eql :running (hngh.domain:run-state run))
             "incomplete or unknown manifest preserves the source run")
      (check (= 1 (getf state :tool-calls))
             "incomplete or unknown manifest invokes tool evidence once")
      (check (= 1 (getf state :repository-calls))
             "incomplete or unknown manifest invokes repository evidence once")
      (check (zerop (getf state :record-calls))
             "incomplete or unknown manifest does not record"))))

(dolist (result-value '(:malformed nil))
  (multiple-value-bind (ports snapshot)
      (make-checkpoint-fake :verification result-value)
    (let ((result (checkpoint-run-with ports (running-application-run)))
          (state (funcall snapshot)))
      (check (eql :refused (checkpoint-result-status result))
             "malformed verification result is refused")
      (check (= 1 (getf state :tool-calls))
             "malformed verification result invokes tool once")
      (check (zerop (getf state :repository-calls))
             "malformed verification result stops repository evidence")
      (check (zerop (getf state :record-calls))
             "malformed verification result does not record"))))

(dolist (result-value '(:malformed nil))
  (multiple-value-bind (ports snapshot)
      (make-checkpoint-fake :manifest result-value)
    (let ((result (checkpoint-run-with ports (running-application-run)))
          (state (funcall snapshot)))
      (check (eql :refused (checkpoint-result-status result))
             "malformed manifest result is refused")
      (check (= 1 (getf state :tool-calls))
             "malformed manifest result invokes tool once")
      (check (= 1 (getf state :repository-calls))
             "malformed manifest result invokes repository once")
      (check (zerop (getf state :record-calls))
             "malformed manifest result does not record"))))

(let ((record-calls 0)
      (repository-calls 0))
  (let ((ports (application-call
                "MAKE-RUN-CHECKPOINT-PORTS"
                :tool-executor (lambda (request)
                                 (declare (ignore request))
                                 (error "tool evidence failed"))
                :repository-inspector (lambda (request)
                                        (declare (ignore request))
                                        (incf repository-calls)
                                        (manifest-result-with))
                :record-run (lambda (run receipt)
                              (declare (ignore run receipt))
                              (incf record-calls)
                              :recorded))))
    (check (eql :refused
                (checkpoint-result-status
                 (checkpoint-run-with ports (running-application-run))))
           "tool evidence callback errors are refused")
    (check (zerop repository-calls)
           "tool evidence callback errors stop repository evidence")
    (check (zerop record-calls)
           "tool evidence callback errors do not record")))

(let ((record-calls 0))
  (let ((ports (application-call
                "MAKE-RUN-CHECKPOINT-PORTS"
                :tool-executor (lambda (request)
                                 (declare (ignore request))
                                 (verification-result-with))
                :repository-inspector (lambda (request)
                                        (declare (ignore request))
                                        (error "repository evidence failed"))
                :record-run (lambda (run receipt)
                              (declare (ignore run receipt))
                              (incf record-calls)
                              :recorded))))
    (check (eql :refused
                (checkpoint-result-status
                 (checkpoint-run-with ports (running-application-run))))
           "repository evidence callback errors are refused")
    (check (zerop record-calls)
           "repository evidence callback errors do not record")))

(multiple-value-bind (ports snapshot)
    (make-checkpoint-fake :record-result :conflict)
  (let ((result (checkpoint-run-with ports (running-application-run)))
        (state (funcall snapshot)))
    (check (eql :conflict (checkpoint-result-status result))
           "checkpoint recording conflict is closed")
    (check (= 1 (getf state :record-calls))
           "checkpoint recording conflict does not retry")
    (check (and (null (getf state :runs)) (null (getf state :receipts)))
           "checkpoint recording conflict stays atomic")))

(multiple-value-bind (ports snapshot)
    (make-checkpoint-fake)
  (let ((source (armed-application-run)))
    (let ((result (checkpoint-run-with ports source))
          (state (funcall snapshot)))
      (check (eql :refused (checkpoint-result-status result))
             "non-running checkpoint source is refused")
      (check (eql :armed (hngh.domain:run-state source))
             "refused checkpoint preserves the source run")
      (check (= 1 (getf state :tool-calls))
             "non-running checkpoint gathers tool evidence once")
      (check (= 1 (getf state :repository-calls))
             "non-running checkpoint gathers repository evidence once")
      (check (zerop (getf state :record-calls))
             "non-running checkpoint does not record"))))

(multiple-value-bind (ports snapshot)
    (make-checkpoint-fake)
  (let ((original (symbol-function 'hngh.domain:advance-run)))
    (unwind-protect
        (progn
          (setf (symbol-function 'hngh.domain:advance-run)
                (lambda (&rest arguments)
                  (declare (ignore arguments))
                  (error "domain transition failed")))
          (check (signals-error-p
                  (lambda ()
                    (checkpoint-run-with ports (running-application-run))))
                 "unexpected checkpoint transition failure remains visible")
          (check (zerop (getf (funcall snapshot) :record-calls))
                 "unexpected checkpoint transition failure does not record"))
      (setf (symbol-function 'hngh.domain:advance-run) original))))
