;;;; core/config.lisp — Hngh configuration loading
;;;;
;;; Loads configuration from ~/.hngh/config/hngh.lisp if it exists.
;;; The config file should contain a plist evaluated as Lisp data, e.g.:
;;;
;;;   (:log-level :debug
;;;    :hngh-home "/home/user/.hngh/"
;;;    :plugin-paths ("/usr/share/hngh/plugins/" "./plugins/"))
;;;
;;; Falls back to defaults if no config file is found.
;;;
;;; SPDX-License-Identifier: AGPL-3.0-or-later
;;; SPDX-FileCopyrightText: 2026 boundring <boundring@gmail.com>

(in-package :hngh.core.config)

(defparameter *default-config*
  '(:log-level :info
    :plugin-paths ("/usr/share/hngh/plugins/")
    :journal-retention-days 30
    :auto-commit-interval-minutes 30)
  "Default configuration plist.")

(defparameter *config* nil
  "Current configuration plist (merged defaults + user config).")

(defun config-path (hngh-home)
  "Return the path to the config file within HNGH-HOME."
  (merge-pathnames "config/hngh.lisp" hngh-home))

(defun load-config-file (path)
  "Load a config file from PATH. Returns a plist or NIL if file doesn't exist."
  (when (probe-file path)
    (hngh.core:log-debug "Loading config from ~A" (namestring path))
    (handler-case
        (with-open-file (stream path :direction :input)
          (let ((*read-eval* nil))
            (let ((form (read stream nil nil)))
              (when (and (listp form) (evenp (length form)))
                form))))
      (error (c)
        (hngh.core:log-warn "Failed to load config from ~A: ~A"
                            (namestring path) c)
        nil))))

(defun merge-config (default user)
  "Merge USER config plist over DEFAULT. User keys override defaults."
  (let ((result (copy-list default)))
    (loop for (key val) on user by #'cddr
          do (setf (getf result key) val))
    result))

(defun load-config (&key (hngh-home nil))
  "Load configuration from the config file, merged with defaults.
Sets *config* and returns it.
HNGH-HOME defaults to hngh:*hngh-home* if not supplied."
  (unless hngh-home
    (setf hngh-home hngh:*hngh-home*))
  (let* ((path (config-path hngh-home))
         (user-config (load-config-file path))
         (merged (merge-config *default-config* user-config)))
    (setf *config* merged)
    (hngh.core:log-debug "Config loaded: ~S" merged)
    merged))

(defun config-get (key &optional default)
  "Get a configuration value by KEY. Returns DEFAULT if not found."
  (getf *config* key default))

(defun config-set (key value)
  "Set a configuration value. Does not persist to file."
  (setf (getf *config* key) value))

(defun save-config (&key (hngh-home nil))
  "Save current configuration to the config file.
HNGH-HOME defaults to hngh:*hngh-home* if not supplied."
  (unless hngh-home
    (setf hngh-home hngh:*hngh-home*))
  (let ((path (config-path hngh-home)))
    (ensure-directories-exist path)
    (with-open-file (stream path :direction :output
                              :if-exists :supersede)
      (format stream ";;; Hngh configuration~%")
      (format stream ";;; Generated by hngh:save-config~%")
      (format stream ";;; Edit manually or via `hngh config set ...`~%~%")
      (let ((*print-case* :downcase))
        (format stream "~S~%" *config*)))
    (hngh.core:log-info "Config saved to ~A" (namestring path))))
